services:
  - type: web
    name: pakjobs-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && playwright install chromium
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: pakjobs-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: false
    healthCheckPath: /health

databases:
  - name: pakjobs-db
    plan: free
    databaseName: pakjobs
    user: pakjobs_user
